### ISSUE TITLE
Wrong resolution on remarkable 1 with X11

### ISSUE THREAD

**Issue by giampierosalvi** [matteodelabre/vnsee#26]
I followed all the instructions for X11 on Ubuntu 20.04 and intel graphic card in combination with a remarkable 1, and using x11vnc. I installed vnsee on the remarkable through Toltec. The only difference from the instructions is that I am not using a launcher, but start vnsee through ssh.

[x11vnc.log](https://github.com/matteodelabre/vnsee/files/6580606/x11vnc.log)
[vnsee.log](https://github.com/matteodelabre/vnsee/files/6580605/vnsee.log)

In attachment you can see the output of x11vnc on the linux machine, and that of vnsee on the remarkable (including the command line). Apparently the remarkable has a different screen resolution that the one suggested in the instructions (1408x3840 instead of the suggested 1404x1872). I wonder if it's enough to change the xrandr addmode command, and in that case, how to get the right parameters to use in that command. Perhaps, if this is the case, the instructions should also mention this possibility.

Let me know if you need more details on the remarkable tablet.

**Comment by giampierosalvi** [comment]
I made it work, meaning I do not get any errors, by using (on the linux machine):
xrandr --newmode 1408x3840 0 1408 1408 1408 1408 3840 3840 3840 3840
xrandr --addmode VIRTUAL1 1408x3840
x11vnc -repeat -forever -nocursor -allow 10.11.99.1 -nopw -clip 1408x3840+1600+0

However, I can barely see the content of the screen on the reMarkable. I saw an hint of the Ubuntu background, and when I moved a window over to that screen I saw the bounding box of the window. But I could not see any content, nor interact with it.

Can it be that I am using the wrong parameters in the newmode command? Or is it a problem with the resolution that is too high? In the last case, how can I make vnsee work with the suggested resolution?

By the way, the version of vnsee is 0.3.1 and the version of x11vnc is 0.9.16.

**Comment by matteodelabre** [comment]
Hi @giampierosalvi!

> Apparently the remarkable has a different screen resolution that the one suggested in the instructions (1408x3840 instead of the suggested 1404x1872). I wonder if it's enough to change the xrandr addmode command, and in that case, how to get the right parameters to use in that command. Perhaps, if this is the case, the instructions should also mention this possibility.

The issue here is that the instructions you followed are intended for VNSee 0.4.0 whereas the version you installed from Toltec is 0.3.1. The old version expected a 1408-pixels-wide resolution and the new one expects a 1404-pixels-wide resolution, for reasons that are detailed in issue #11. However, it should be enough to change the arguments given to xrandr (as you mentioned) to make it work.

I wrote the docs thinking that the package in Toltec would be updated fairly soon after, but it’s only been updated to 0.4.0 in the testing branch today and it will likely be a few weeks before it lands in the stable branch. In the meantime, I suggest you download and install the latest release manually from <https://github.com/matteodelabre/vnsee/releases/tag/v0.4.0>. I will update the README today to mention this, sorry that this was a bit confusing (see also #25).

> I made it work, meaning I do not get any errors, by using (on the linux machine):
> xrandr --newmode 1408x3840 0 1408 1408 1408 1408 3840 3840 3840 3840
> xrandr --addmode VIRTUAL1 1408x3840
> x11vnc -repeat -forever -nocursor -allow 10.11.99.1 -nopw -clip 1408x3840+1600+0
> 
> However, I can barely see the content of the screen on the reMarkable. I saw an hint of the Ubuntu background, and when I moved a window over to that screen I saw the bounding box of the window. But I could not see any content, nor interact with it.

Did you enable the virtual display after setting it up? This can be done either by running the command below or by using a graphical multi-screen setup program, such as the ones shipped with GNOME and KDE.

```
$ xrandr --output VIRTUAL1 --mode 1408x1872 --right-of DP1
```

(You should substitute DP1 with the name of the screen relative to which you wish to place the virtual output.)

**Comment by giampierosalvi** [comment]
Hi @matteodelabre ,
thank you, now things are clearer. I did run the command you mentioned to enable the virtual display, and the display was indeed active because I could see something on it related to what I was doing on the computer. But could not see the content properly. However, now I have downloaded version 0.4.0 and it works as expected.

**Comment by matteodelabre** [comment]
Great! Happy to help.
